baseURL = 'https://lamjan.com/'
languageCode = 'en-us'
title = 'lamjan'
theme = 'PaperMod'

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
description = "Clear, simple, and step-by-step guides for general cloud setups and phone software diagnostics."
author = "lamjan"
defaultTheme = "auto"
ShowCodeCopyButtons = true
comments = true

# CLEAN TOP LABEL BRANDING
[params.label]
text = "lamjan"
icon = "/images/logo.svg"
iconHeight = 35

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"

# BROAD APPROACHABLE NAVIGATION STREAMS
[[menu.main]]
name = "Cloud Computing"
url = "/categories/cloud-computing/"
weight = 10

[[menu.main]]
name = "Mobile"
url = "/categories/mobile/"
weight = 20

[[menu.main]]
name = "All Posts"
url = "/posts/"
weight = 30

# CLEAN FOOTER LAYOUT WITH GITHUB
[params.footer]
showPoweredBy = false

[[params.socialIcons]]
name = "github"
url = "https://github.com/lamjan-t"
[markup.goldmark.renderer]
unsafe = true